---
kind: pipeline
name: publish-image
steps:
- name: publish
  image: militarpancho1/drone-plugins-gcr:20.10.8
  privileged: true
  settings:
    mtu: 1460
    json_key:
      from_secret: GCR_TOKEN
    registry: europe-west1-docker.pkg.dev
    repo: europe-west1-docker.pkg.dev/graphext-development/docker/acyl
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - deploy
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 75bf79da2e218e49e31448c25f443f610572540b46a2dfee0f5a969ca73711ae

...
