---
kind: pipeline
name: publish-image
steps:
- name: publish
  image: militarpancho1/drone-plugins-gcr:20.10.8
  privileged: true
  settings:
    mtu: 1460
    json_key:
      from_secret: GCR_TOKEN
    registry: eu.gcr.io
    repo: europe-west1-docker.pkg.dev/graphext-development/docker/acyl
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - deploy
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: c488b9e6efdaba480a2d0cf47f1d3022ebd19536184eca8a7f2882a5f654893b

...
