// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Acyl
//
//  The Acyl API provides authenticated users an array of options to create and manage dynamic environments.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: v0.7.6
//  License: MIT
//  Contact: Benjamen Keroack<benjamen@dollarshaveclub.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
