// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "The Acyl API provides authenticated users an array of options to create and manage dynamic environments.",
    "title": "Acyl",
    "contact": {
      "name": "Benjamen Keroack",
      "email": "benjamen@dollarshaveclub.com"
    },
    "license": {
      "name": "MIT"
    },
    "version": "v0.7.6"
  },
  "paths": {
    "/env/envname": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ui"
        ],
        "summary": "returns status page",
        "operationId": "getEnv",
        "parameters": [
          {
            "type": "string",
            "description": "event log identifier",
            "name": "envname",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success, render environment page"
          },
          "400": {
            "description": "bad request getting environment page for envname, or permitted repository"
          },
          "401": {
            "description": "unauthorized github user session"
          },
          "404": {
            "description": "environment page not found for envname"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/event/status": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ui"
        ],
        "summary": "returns status page",
        "operationId": "getStatus",
        "parameters": [
          {
            "type": "string",
            "description": "event log identifier",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success, render status page"
          },
          "400": {
            "description": "bad request getting status page for id"
          },
          "401": {
            "description": "unauthorized github user session"
          },
          "404": {
            "description": "status page not found for id"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/home": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ui"
        ],
        "summary": "returns home page",
        "operationId": "getHome",
        "responses": {
          "200": {
            "description": "success, render status page"
          },
          "401": {
            "description": "unauthorized github user session"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "user interface endpoints",
      "name": "ui"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "The Acyl API provides authenticated users an array of options to create and manage dynamic environments.",
    "title": "Acyl",
    "contact": {
      "name": "Benjamen Keroack",
      "email": "benjamen@dollarshaveclub.com"
    },
    "license": {
      "name": "MIT"
    },
    "version": "v0.7.6"
  },
  "paths": {
    "/env/envname": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ui"
        ],
        "summary": "returns status page",
        "operationId": "getEnv",
        "parameters": [
          {
            "type": "string",
            "description": "event log identifier",
            "name": "envname",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success, render environment page"
          },
          "400": {
            "description": "bad request getting environment page for envname, or permitted repository"
          },
          "401": {
            "description": "unauthorized github user session"
          },
          "404": {
            "description": "environment page not found for envname"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/event/status": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ui"
        ],
        "summary": "returns status page",
        "operationId": "getStatus",
        "parameters": [
          {
            "type": "string",
            "description": "event log identifier",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success, render status page"
          },
          "400": {
            "description": "bad request getting status page for id"
          },
          "401": {
            "description": "unauthorized github user session"
          },
          "404": {
            "description": "status page not found for id"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    },
    "/home": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ui"
        ],
        "summary": "returns home page",
        "operationId": "getHome",
        "responses": {
          "200": {
            "description": "success, render status page"
          },
          "401": {
            "description": "unauthorized github user session"
          },
          "500": {
            "description": "internal server error"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "user interface endpoints",
      "name": "ui"
    }
  ]
}`))
}
