// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetEnvOKCode is the HTTP code returned for type GetEnvOK
const GetEnvOKCode int = 200

/*GetEnvOK success, render environment page

swagger:response getEnvOK
*/
type GetEnvOK struct {
}

// NewGetEnvOK creates GetEnvOK with default headers values
func NewGetEnvOK() *GetEnvOK {

	return &GetEnvOK{}
}

// WriteResponse to the client
func (o *GetEnvOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetEnvBadRequestCode is the HTTP code returned for type GetEnvBadRequest
const GetEnvBadRequestCode int = 400

/*GetEnvBadRequest bad request getting environment page for envname, or permitted repository

swagger:response getEnvBadRequest
*/
type GetEnvBadRequest struct {
}

// NewGetEnvBadRequest creates GetEnvBadRequest with default headers values
func NewGetEnvBadRequest() *GetEnvBadRequest {

	return &GetEnvBadRequest{}
}

// WriteResponse to the client
func (o *GetEnvBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetEnvUnauthorizedCode is the HTTP code returned for type GetEnvUnauthorized
const GetEnvUnauthorizedCode int = 401

/*GetEnvUnauthorized unauthorized github user session

swagger:response getEnvUnauthorized
*/
type GetEnvUnauthorized struct {
}

// NewGetEnvUnauthorized creates GetEnvUnauthorized with default headers values
func NewGetEnvUnauthorized() *GetEnvUnauthorized {

	return &GetEnvUnauthorized{}
}

// WriteResponse to the client
func (o *GetEnvUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetEnvNotFoundCode is the HTTP code returned for type GetEnvNotFound
const GetEnvNotFoundCode int = 404

/*GetEnvNotFound environment page not found for envname

swagger:response getEnvNotFound
*/
type GetEnvNotFound struct {
}

// NewGetEnvNotFound creates GetEnvNotFound with default headers values
func NewGetEnvNotFound() *GetEnvNotFound {

	return &GetEnvNotFound{}
}

// WriteResponse to the client
func (o *GetEnvNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetEnvInternalServerErrorCode is the HTTP code returned for type GetEnvInternalServerError
const GetEnvInternalServerErrorCode int = 500

/*GetEnvInternalServerError internal server error

swagger:response getEnvInternalServerError
*/
type GetEnvInternalServerError struct {
}

// NewGetEnvInternalServerError creates GetEnvInternalServerError with default headers values
func NewGetEnvInternalServerError() *GetEnvInternalServerError {

	return &GetEnvInternalServerError{}
}

// WriteResponse to the client
func (o *GetEnvInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
