// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetStatusOKCode is the HTTP code returned for type GetStatusOK
const GetStatusOKCode int = 200

/*GetStatusOK success, render status page

swagger:response getStatusOK
*/
type GetStatusOK struct {
}

// NewGetStatusOK creates GetStatusOK with default headers values
func NewGetStatusOK() *GetStatusOK {

	return &GetStatusOK{}
}

// WriteResponse to the client
func (o *GetStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetStatusBadRequestCode is the HTTP code returned for type GetStatusBadRequest
const GetStatusBadRequestCode int = 400

/*GetStatusBadRequest bad request getting status page for id

swagger:response getStatusBadRequest
*/
type GetStatusBadRequest struct {
}

// NewGetStatusBadRequest creates GetStatusBadRequest with default headers values
func NewGetStatusBadRequest() *GetStatusBadRequest {

	return &GetStatusBadRequest{}
}

// WriteResponse to the client
func (o *GetStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetStatusUnauthorizedCode is the HTTP code returned for type GetStatusUnauthorized
const GetStatusUnauthorizedCode int = 401

/*GetStatusUnauthorized unauthorized github user session

swagger:response getStatusUnauthorized
*/
type GetStatusUnauthorized struct {
}

// NewGetStatusUnauthorized creates GetStatusUnauthorized with default headers values
func NewGetStatusUnauthorized() *GetStatusUnauthorized {

	return &GetStatusUnauthorized{}
}

// WriteResponse to the client
func (o *GetStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetStatusNotFoundCode is the HTTP code returned for type GetStatusNotFound
const GetStatusNotFoundCode int = 404

/*GetStatusNotFound status page not found for id

swagger:response getStatusNotFound
*/
type GetStatusNotFound struct {
}

// NewGetStatusNotFound creates GetStatusNotFound with default headers values
func NewGetStatusNotFound() *GetStatusNotFound {

	return &GetStatusNotFound{}
}

// WriteResponse to the client
func (o *GetStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetStatusInternalServerErrorCode is the HTTP code returned for type GetStatusInternalServerError
const GetStatusInternalServerErrorCode int = 500

/*GetStatusInternalServerError internal server error

swagger:response getStatusInternalServerError
*/
type GetStatusInternalServerError struct {
}

// NewGetStatusInternalServerError creates GetStatusInternalServerError with default headers values
func NewGetStatusInternalServerError() *GetStatusInternalServerError {

	return &GetStatusInternalServerError{}
}

// WriteResponse to the client
func (o *GetStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
