// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEnvHandlerFunc turns a function with the right signature into a get env handler
type GetEnvHandlerFunc func(GetEnvParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEnvHandlerFunc) Handle(params GetEnvParams) middleware.Responder {
	return fn(params)
}

// GetEnvHandler interface for that can handle valid get env params
type GetEnvHandler interface {
	Handle(GetEnvParams) middleware.Responder
}

// NewGetEnv creates a new http.Handler for the get env operation
func NewGetEnv(ctx *middleware.Context, handler GetEnvHandler) *GetEnv {
	return &GetEnv{Context: ctx, Handler: handler}
}

/*GetEnv swagger:route GET /env/envname ui getEnv

returns status page

*/
type GetEnv struct {
	Context *middleware.Context
	Handler GetEnvHandler
}

func (o *GetEnv) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEnvParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
