// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHomeOKCode is the HTTP code returned for type GetHomeOK
const GetHomeOKCode int = 200

/*GetHomeOK success, render status page

swagger:response getHomeOK
*/
type GetHomeOK struct {
}

// NewGetHomeOK creates GetHomeOK with default headers values
func NewGetHomeOK() *GetHomeOK {

	return &GetHomeOK{}
}

// WriteResponse to the client
func (o *GetHomeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetHomeUnauthorizedCode is the HTTP code returned for type GetHomeUnauthorized
const GetHomeUnauthorizedCode int = 401

/*GetHomeUnauthorized unauthorized github user session

swagger:response getHomeUnauthorized
*/
type GetHomeUnauthorized struct {
}

// NewGetHomeUnauthorized creates GetHomeUnauthorized with default headers values
func NewGetHomeUnauthorized() *GetHomeUnauthorized {

	return &GetHomeUnauthorized{}
}

// WriteResponse to the client
func (o *GetHomeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetHomeInternalServerErrorCode is the HTTP code returned for type GetHomeInternalServerError
const GetHomeInternalServerErrorCode int = 500

/*GetHomeInternalServerError internal server error

swagger:response getHomeInternalServerError
*/
type GetHomeInternalServerError struct {
}

// NewGetHomeInternalServerError creates GetHomeInternalServerError with default headers values
func NewGetHomeInternalServerError() *GetHomeInternalServerError {

	return &GetHomeInternalServerError{}
}

// WriteResponse to the client
func (o *GetHomeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
