// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetEnvParams creates a new GetEnvParams object
// no default values defined in spec.
func NewGetEnvParams() GetEnvParams {

	return GetEnvParams{}
}

// GetEnvParams contains all the bound params for the get env operation
// typically these are obtained from a http.Request
//
// swagger:parameters getEnv
type GetEnvParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*event log identifier
	  Required: true
	  In: query
	*/
	Envname string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEnvParams() beforehand.
func (o *GetEnvParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEnvname, qhkEnvname, _ := qs.GetOK("envname")
	if err := o.bindEnvname(qEnvname, qhkEnvname, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEnvname binds and validates parameter Envname from query.
func (o *GetEnvParams) bindEnvname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("envname", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("envname", "query", raw); err != nil {
		return err
	}

	o.Envname = raw

	return nil
}
