// Code generated by go-swagger; DO NOT EDIT.

package ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetHomeHandlerFunc turns a function with the right signature into a get home handler
type GetHomeHandlerFunc func(GetHomeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHomeHandlerFunc) Handle(params GetHomeParams) middleware.Responder {
	return fn(params)
}

// GetHomeHandler interface for that can handle valid get home params
type GetHomeHandler interface {
	Handle(GetHomeParams) middleware.Responder
}

// NewGetHome creates a new http.Handler for the get home operation
func NewGetHome(ctx *middleware.Context, handler GetHomeHandler) *GetHome {
	return &GetHome{Context: ctx, Handler: handler}
}

/*GetHome swagger:route GET /home ui getHome

returns home page

*/
type GetHome struct {
	Context *middleware.Context
	Handler GetHomeHandler
}

func (o *GetHome) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHomeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
